all:
	javac dungeonfighter/DungeonFighter.java -d bin

	cp -r dungeonfighter/assets .

	java -cp bin/ dungeonfighter.DungeonFighter

run:
	java -cp bin/ dungeonfighter.DungeonFighter


bin:
	javac dungeonfighter/DungeonFighter.java -d bin

	cp -r dungeonfighter/assets .

clean:
	rm -rf bin assets
